---
- name: Check if secrets file already exists
  ansible.builtin.stat:
    path: "{{ output_directory }}/secrets.yaml"
  register: secrets_file

- name: Generate Talos secrets
  ansible.builtin.command:
    cmd: talosctl gen secrets -o {{ output_directory }}/secrets.yaml
  when: not secrets_file.stat.exists
